name: hourly-update
on:
  schedule:
  # 毎時0分にデプロイ
    - cron: '0 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    env:
      VERCEL_DEPLOY_HOOK_URL: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
    steps:
      - name: Vercel Depoloy
        run: |
          curl --request POST \
          --url "$VERCEL_DEPLOY_HOOK_URL"