name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    # vercelのデフォルトはver.18.x
    # https://vercel.com/docs/concepts/functions/serverless-functions/runtimes/node-js
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn run build
