name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          # vercelのデフォルトはver.18.x
          # https://vercel.com/docs/concepts/functions/serverless-functions/runtimes/node-js
          node-version: "18.x"
      - run: yarn install
      # 環境変数の設定が必要なので一旦コメントアウト
      # - run: yarn run build
